name: Deploy to Kubernetes

# TRIGGERS:
on:
  push:
    branches: [ master ]  # Triggers on every push to master
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Get your code
    - name: Checkout code
      uses: actions/checkout@v3
    
    # 2. Build and push Docker images
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push frontend
      run: |
        docker build -t v1v3kr/my-react-app:${{ github.sha }} .
        docker push v1v3kr/my-react-app:${{ github.sha }}
    
    - name: Build and push backend
      run: |
        cd backend
        docker build -t v1v3kr/my-backend-app:${{ github.sha }} .
        docker push v1v3kr/my-backend-app:${{ github.sha }}
    
    # 3. Deploy to Kubernetes (if you have cloud cluster)
    - name: Deploy to Kubernetes
      run: |
        # Update image tags in K8s files
        sed -i 's|v1v3kr/my-react-app:latest|v1v3kr/my-react-app:${{ github.sha }}|' k8s/frontend-deployment.yaml
        sed -i 's|v1v3kr/my-backend-app:latest|v1v3kr/my-backend-app:${{ github.sha }}|' k8s/backend-deployment.yaml
        
        # Apply to cluster (needs kubectl configured)
        kubectl apply -f k8s/
