name: Security Scan

on:
  push:
    branches: [ master, main ]
  schedule:
    # Run security scan weekly
    - cron: '0 2 * * 1'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install frontend dependencies
      run: |
        npm ci
        
    - name: Install backend dependencies
      run: |
        cd backend
        npm ci
        
    - name: Run frontend security audit
      run: npm audit --audit-level=high
      continue-on-error: true
      
    - name: Run backend security audit
      run: |
        cd backend
        npm audit --audit-level=high
      continue-on-error: true
